### ISSUE TITLE
他MODとの干渉チェック

### ISSUE THREAD

**Issue by himesama1301** [himesama1301/MizuMod#79]
自分で気付いた、指摘されたものをチェックする。
- [x] Hospitality
  - 客が水を飲まず脱水症状を起こした(ブロマガより)
- [x] Dubs Bad Hygiene
  - ぎりぎりまで便をため込むような挙動を見せた(ブロマガより)
- [x] EdB Prepare Carefully
  - シナリオ追加の水アイテムがポッドから出るのではなく最初から地面に落ちている(#88)(自分で発見)

**Comment by himesama1301** [comment]
実は水MODのみの環境でトレーダーや旅行者が水を飲まないのではないかと思って調べてみたが、ちゃんと飲んでた。
他MODとの干渉による現象のようだ。

**Comment by himesama1301** [comment]
ありそうな原因。
バグ報告者は水MODを該当MODより上に置いていた可能性がある。
MODの並び順で、水MODを下に置けば解決するような気がする。
上でも下でも動作するように出来ればよいのだが。

**Comment by himesama1301** [comment]
EdB Prepare Carefully
MODを水MODとEdBのみにしてチェック。
水MODが上の状態で通常スタート→ポッドから水アイテムが出る
水MODが上の状態でEdBスタート→水アイテムが落ちてる

**Comment by himesama1301** [comment]
シナリオへのアイテム追加方法を変更してみたり、MODの並び順を上下逆にしてみたりしたけど変わらなかった。通常スタートでは今の追加方法でちゃんと出てくるので、PrepareCarefully側の何かが変なのではないかと思う。
調査したところでポッドから出てくるかどうかが変わるだけで大した変化じゃないのでこの調査はここで終了。

**Comment by himesama1301** [comment]
調査の発端となったコメントを再確認。読み違えてたかもしれない。
ホスピタリティで訪れた客が、水を携帯しているけど飲まず脱水症状を起こしていた。
同様にホスピタリティで訪れた客がトイレもギリギリまで我慢していた。
ということか？
とりあえずホスピタリティと水MODのチェックをする。

**Comment by himesama1301** [comment]
ホスピタリティ上、水MOD下→食事する、娯楽設備使う、水は飲まない
水MOD上、ホスピタリティ下→調査中

**Comment by himesama1301** [comment]
Hospitalityによる客の行動はThinkTreeDefではなくDutyDefで定義されている？
(ThinkTreeDefが一つも入ってないので)
二つの違いがよくわからないが……
水MODはThinkTreeDefのほうしか調整していないので、おそらくこれが原因。

**Comment by himesama1301** [comment]
DutyDefのほうにも水飲み行動を加えた結果
MOD順(上から)
HugsLib、ホスピタリティ、水MOD→食事する、娯楽設備使う、水は飲まない
HugsLib、水MOD、ホスピタリティ→水を飲んだ
置いてあるきれいな水ではなく手持ちの生水を飲んだが、これは水スコアの関係か？

**Comment by himesama1301** [comment]
ついでにHospitalityで水を購入するかチェック
MOD順(上から)
HugsLib、ホスピタリティ、水MOD→買わない
HugsLib、水MOD、ホスピタリティ→調査中

**Comment by himesama1301** [comment]
MOD内容を見た感じ、Hospitalityで購入するのはFoodかStuff(素材?)だけのようだ。
スチールを購入している場面は見た。

**Comment by himesama1301** [comment]
Dubsの方もチェックした。
トイレ行動、風呂行動がThinkTreeDefにしか追加されていないため、修正前の水MODと同様にHospitalityの客はその設備を使わないだろう。

**Comment by himesama1301** [comment]
今回の調査で分かったことは、Patchによる要素の追加はMODの並び順が関係ないかもしれないということ。
DefとAssemblyのロードをMOD順に行った後、改めて上から順にPatchを当てるという処理なのかもしれない。
今のところ調査の必要がないので調べないけど。

**Comment by OrionFive** [comment]
Hi,
I have currently listed your mod as incompatible with Hospitality. Is this still the case or are they compatible now?
I saw the issue that guests don't buy water. Were you able to fix that? Guests will buy food if they are hungry and random objects if they are bored and have money left. I don't think I should hardcode buying behavior for specific mods. Any ideas how this could be solved?

**Comment by himesama1301** [comment]
I'm sorry. I have stopped developing this mod. This mod only supports to RimWorld version B18, but even then the compatibility with Hosipitality was not perfect.
